<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-L2IPGEE" failures="1" tests="1" name="runner.Runner" time="24.708" errors="0" timestamp="2023-11-30T10:23:47 BDT" skipped="0">
  <testcase classname="runner.Runner" name="runScenario" time="24.708">
    <failure message="expected [Customer Id: 4] but found [Customer Id: 444]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Customer Id: 4] but found [Customer Id: 444]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at steps.LoginFeatureValidations.verify_that_i_am_in_customer_home_page(LoginFeatureValidations.java:75)
at âœ½.Verify that I am in CUSTOMER Home Page(file:///D:/Project/PlayWright-project/CucumberBDDPlaywright23%20-%20Copy/src/test/resources/features/LoginFeatureValidations.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.Runner -->
